import 'package:flutter/material.dart';

class Theme {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF),
    onPrimary: Color(0xFF),
    primaryContainer: Color(0xFF),
    onPrimaryContainer: Color(0xFF),
    secondary: Color(0xFF),
    onSecondary: Color(0xFF),
    secondaryContainer: Color(0xFF),
    onSecondaryContainer: Color(0xFF),
    tertiary: Color(0xFF),
    onTertiary: Color(0xFF),
    tertiaryContainer: Color(0xFF),
    onTertiaryContainer: Color(0xFF),
    error: Color(0xFF),
    onError: Color(0xFF),
    errorContainer: Color(0xFF),
    onErrorContainer: Color(0xFF),
    surfaceDim: Color(0xFF),
    surface: Color(0xFF),
    surfaceBright: Color(0xFF),
    surfaceContainerLowest: Color(0xFF),
    surfaceContainerLow: Color(0xFF),
    surfaceContainer: Color(0xFF),
    surfaceContainerHigh: Color(0xFF),
    surfaceContainerHighest: Color(0xFF),
    onSurface: Color(0xFF),
    onSurfaceVariant: Color(0xFF),
    outline: Color(0xFF),
    outlineVariant: Color(0xFF),
    inverseSurface: Color(0xFF),
    onInverseSurface: Color(0xFF),
    inversePrimary: Color(0xFF),
    scrim: Color(0xFF),
    shadow: Color(0xFF),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF),
    onPrimary: Color(0xFF),
    primaryContainer: Color(0xFF),
    onPrimaryContainer: Color(0xFF),
    secondary: Color(0xFF),
    onSecondary: Color(0xFF),
    secondaryContainer: Color(0xFF),
    onSecondaryContainer: Color(0xFF),
    tertiary: Color(0xFF),
    onTertiary: Color(0xFF),
    tertiaryContainer: Color(0xFF),
    onTertiaryContainer: Color(0xFF),
    error: Color(0xFF),
    onError: Color(0xFF),
    errorContainer: Color(0xFF),
    onErrorContainer: Color(0xFF),
    surfaceDim: Color(0xFF),
    surface: Color(0xFF),
    surfaceBright: Color(0xFF),
    surfaceContainerLowest: Color(0xFF),
    surfaceContainerLow: Color(0xFF),
    surfaceContainer: Color(0xFF),
    surfaceContainerHigh: Color(0xFF),
    surfaceContainerHighest: Color(0xFF),
    onSurface: Color(0xFF),
    onSurfaceVariant: Color(0xFF),
    outline: Color(0xFF),
    outlineVariant: Color(0xFF),
    inverseSurface: Color(0xFF),
    onInverseSurface: Color(0xFF),
    inversePrimary: Color(0xFF),
    scrim: Color(0xFF),
    shadow: Color(0xFF),
  );
}